# -*- coding: utf-8 -*-
"""Copy of simple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hgk4a7i8bzet2MpOlC_WJbd5r0sNJjc4

# Simple Linear Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Salary_Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(x_test)

"""## Visualising the Training set results"""

plt.scatter(x_train, y_train, color = 'red') #real data points
plt.plot(x_train,regressor.predict(x_train), color = 'orange'  ) #linear Regression
plt.title('Salary vs Experience (training set)')
plt.xlabel('Years of Excperience')
plt.ylabel('Salary')
plt.show()

"""## Visualising the Test set results"""

plt.scatter(x_test, y_test, color = 'red') #real data points
plt.plot(x_train,regressor.predict(x_train), color = 'blue'  ) #linear Regression
plt.title('Salary vs Experience (testing set)')
plt.xlabel('Years of Excperience')
plt.ylabel('Salary')
plt.show()